export const stockDatabase = [
    { symbol: 'AAPL', name: 'Apple Inc.', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'MSFT', name: 'Microsoft Corporation', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'GOOGL', name: 'Alphabet Inc.', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'AMZN', name: 'Amazon.com Inc.', exchange: 'NASDAQ', type: 'Consumer Cyclical' },
    { symbol: 'TSLA', name: 'Tesla Inc.', exchange: 'NASDAQ', type: 'Automotive' },
    { symbol: 'NVDA', name: 'NVIDIA Corporation', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'META', name: 'Meta Platforms Inc.', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'BRK.B', name: 'Berkshire Hathaway', exchange: 'NYSE', type: 'Financial' },
    { symbol: 'JPM', name: 'JPMorgan Chase & Co.', exchange: 'NYSE', type: 'Financial' },
    { symbol: 'V', name: 'Visa Inc.', exchange: 'NYSE', type: 'Financial' },
    { symbol: 'UNH', name: 'UnitedHealth Group', exchange: 'NYSE', type: 'Healthcare' },
    { symbol: 'XOM', name: 'Exxon Mobil Corporation', exchange: 'NYSE', type: 'Energy' },
    { symbol: 'JNJ', name: 'Johnson & Johnson', exchange: 'NYSE', type: 'Healthcare' },
    { symbol: 'WMT', name: 'Walmart Inc.', exchange: 'NYSE', type: 'Retail' },
    { symbol: 'PG', name: 'Procter & Gamble', exchange: 'NYSE', type: 'Consumer Goods' },
    { symbol: 'MA', name: 'Mastercard Inc.', exchange: 'NYSE', type: 'Financial' },
    { symbol: 'HD', name: 'The Home Depot', exchange: 'NYSE', type: 'Retail' },
    { symbol: 'CVX', name: 'Chevron Corporation', exchange: 'NYSE', type: 'Energy' },
    { symbol: 'ABBV', name: 'AbbVie Inc.', exchange: 'NYSE', type: 'Healthcare' },
    { symbol: 'PFE', name: 'Pfizer Inc.', exchange: 'NYSE', type: 'Healthcare' },
    { symbol: 'KO', name: 'The Coca-Cola Company', exchange: 'NYSE', type: 'Beverages' },
    { symbol: 'AVGO', name: 'Broadcom Inc.', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'PEP', name: 'PepsiCo Inc.', exchange: 'NASDAQ', type: 'Beverages' },
    { symbol: 'COST', name: 'Costco Wholesale', exchange: 'NASDAQ', type: 'Retail' },
    { symbol: 'TMO', name: 'Thermo Fisher Scientific', exchange: 'NYSE', type: 'Healthcare' },
    { symbol: 'MRK', name: 'Merck & Co.', exchange: 'NYSE', type: 'Healthcare' },
    { symbol: 'CSCO', name: 'Cisco Systems', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'ACN', name: 'Accenture plc', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'ADBE', name: 'Adobe Inc.', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'TXN', name: 'Texas Instruments', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'LIN', name: 'Linde plc', exchange: 'NYSE', type: 'Chemicals' },
    { symbol: 'DHR', name: 'Danaher Corporation', exchange: 'NYSE', type: 'Healthcare' },
    { symbol: 'NKE', name: 'Nike Inc.', exchange: 'NYSE', type: 'Consumer Cyclical' },
    { symbol: 'ABT', name: 'Abbott Laboratories', exchange: 'NYSE', type: 'Healthcare' },
    { symbol: 'ORCL', name: 'Oracle Corporation', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'CRM', name: 'Salesforce Inc.', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'VZ', name: 'Verizon Communications', exchange: 'NYSE', type: 'Telecommunications' },
    { symbol: 'INTC', name: 'Intel Corporation', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'AMD', name: 'Advanced Micro Devices', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'NFLX', name: 'Netflix Inc.', exchange: 'NASDAQ', type: 'Entertainment' },
    { symbol: 'CMCSA', name: 'Comcast Corporation', exchange: 'NASDAQ', type: 'Telecommunications' },
    { symbol: 'DIS', name: 'The Walt Disney Company', exchange: 'NYSE', type: 'Entertainment' },
    { symbol: 'QCOM', name: 'Qualcomm Inc.', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'BA', name: 'The Boeing Company', exchange: 'NYSE', type: 'Aerospace' },
    { symbol: 'IBM', name: 'IBM', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'GE', name: 'General Electric', exchange: 'NYSE', type: 'Industrial' },
    { symbol: 'CAT', name: 'Caterpillar Inc.', exchange: 'NYSE', type: 'Industrial' },
    { symbol: 'GS', name: 'Goldman Sachs Group', exchange: 'NYSE', type: 'Financial' },
    { symbol: 'MS', name: 'Morgan Stanley', exchange: 'NYSE', type: 'Financial' },
    { symbol: 'AXP', name: 'American Express', exchange: 'NYSE', type: 'Financial' },
    { symbol: 'BLK', name: 'BlackRock Inc.', exchange: 'NYSE', type: 'Financial' },
    { symbol: 'SPGI', name: 'S&P Global Inc.', exchange: 'NYSE', type: 'Financial' },
    { symbol: 'MMM', name: '3M Company', exchange: 'NYSE', type: 'Industrial' },
    { symbol: 'HON', name: 'Honeywell International', exchange: 'NASDAQ', type: 'Industrial' },
    { symbol: 'UNP', name: 'Union Pacific Corporation', exchange: 'NYSE', type: 'Transportation' },
    { symbol: 'RTX', name: 'Raytheon Technologies', exchange: 'NYSE', type: 'Aerospace' },
    { symbol: 'LMT', name: 'Lockheed Martin', exchange: 'NYSE', type: 'Aerospace' },
    { symbol: 'DE', name: 'Deere & Company', exchange: 'NYSE', type: 'Industrial' },
    { symbol: 'SBUX', name: 'Starbucks Corporation', exchange: 'NASDAQ', type: 'Consumer Cyclical' },
    { symbol: 'MCD', name: 'McDonald\'s Corporation', exchange: 'NYSE', type: 'Consumer Cyclical' },
    { symbol: 'TGT', name: 'Target Corporation', exchange: 'NYSE', type: 'Retail' },
    { symbol: 'LOW', name: 'Lowe\'s Companies', exchange: 'NYSE', type: 'Retail' },
    { symbol: 'AMGN', name: 'Amgen Inc.', exchange: 'NASDAQ', type: 'Healthcare' },
    { symbol: 'GILD', name: 'Gilead Sciences', exchange: 'NASDAQ', type: 'Healthcare' },
    { symbol: 'BKNG', name: 'Booking Holdings', exchange: 'NASDAQ', type: 'Travel' },
    { symbol: 'ISRG', name: 'Intuitive Surgical', exchange: 'NASDAQ', type: 'Healthcare' },
    { symbol: 'NOW', name: 'ServiceNow Inc.', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'PYPL', name: 'PayPal Holdings', exchange: 'NASDAQ', type: 'Financial' },
    { symbol: 'SQ', name: 'Block Inc.', exchange: 'NYSE', type: 'Financial' },
    { symbol: 'SHOP', name: 'Shopify Inc.', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'UBER', name: 'Uber Technologies', exchange: 'NYSE', type: 'Transportation' },
    { symbol: 'ABNB', name: 'Airbnb Inc.', exchange: 'NASDAQ', type: 'Travel' },
    { symbol: 'COIN', name: 'Coinbase Global', exchange: 'NASDAQ', type: 'Financial' },
    { symbol: 'ROKU', name: 'Roku Inc.', exchange: 'NASDAQ', type: 'Entertainment' },
    { symbol: 'SNAP', name: 'Snap Inc.', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'SPOT', name: 'Spotify Technology', exchange: 'NYSE', type: 'Entertainment' },
    { symbol: 'ZM', name: 'Zoom Video Communications', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'DOCU', name: 'DocuSign Inc.', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'CRWD', name: 'CrowdStrike Holdings', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'NET', name: 'Cloudflare Inc.', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'SNOW', name: 'Snowflake Inc.', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'PLTR', name: 'Palantir Technologies', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'RBLX', name: 'Roblox Corporation', exchange: 'NYSE', type: 'Entertainment' },
    { symbol: 'U', name: 'Unity Software', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'DKNG', name: 'DraftKings Inc.', exchange: 'NASDAQ', type: 'Entertainment' },
    { symbol: 'RIVN', name: 'Rivian Automotive', exchange: 'NASDAQ', type: 'Automotive' },
    { symbol: 'LCID', name: 'Lucid Group', exchange: 'NASDAQ', type: 'Automotive' },
    { symbol: 'F', name: 'Ford Motor Company', exchange: 'NYSE', type: 'Automotive' },
    { symbol: 'GM', name: 'General Motors', exchange: 'NYSE', type: 'Automotive' },
    { symbol: 'NIO', name: 'NIO Inc.', exchange: 'NYSE', type: 'Automotive' },
    { symbol: 'BABA', name: 'Alibaba Group', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'JD', name: 'JD.com Inc.', exchange: 'NASDAQ', type: 'Retail' },
    { symbol: 'PDD', name: 'PDD Holdings', exchange: 'NASDAQ', type: 'Retail' },
    { symbol: 'BIDU', name: 'Baidu Inc.', exchange: 'NASDAQ', type: 'Technology' },
    { symbol: 'TSM', name: 'Taiwan Semiconductor', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'SONY', name: 'Sony Group Corporation', exchange: 'NYSE', type: 'Entertainment' },
    { symbol: 'TM', name: 'Toyota Motor Corporation', exchange: 'NYSE', type: 'Automotive' },
    { symbol: 'SAP', name: 'SAP SE', exchange: 'NYSE', type: 'Technology' },
    { symbol: 'ASML', name: 'ASML Holding', exchange: 'NASDAQ', type: 'Technology' },
  ];
  export const popularStocks = stockDatabase.slice(0, 10);